cache:
  type: dragonfly
  dragonfly:
    host: localhost
    port: 6379
    timeout: 10000
  idempotent.ttl: PT5M



db:
  type: postgresql
  postgresql:
    host: localhost
    port: 5432
    database: demodb
    username: demouser
    password: demopass